# #price_predictor

In [1]:
import pandas as pd
import numpy as np

In [2]:
housing = pd.read_csv('data.csv')

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
housing['CHAS'].value_counts()

0    471
1     35
Name: CHAS, dtype: int64

In [6]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284341   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.705587   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [7]:
%matplotlib inline

In [8]:
#for ploting histogram
# import matplotlib.pyplot as plt
# housing.hist(bins=50,figsize=(20,15))
# plt.show()

## Train -Test Splitting

In [9]:
# import numpy as np
# def split_train_test(data,test_ratio):
#     np.random.seed(42)
#     shuffled=np.random.permutation(len(data))
#     print(shuffled)
#     test_set_size=int(len(data)*test_ratio)
#     test_indices=shuffled[:test_set_size]
#     train_indices=shuffled[test_set_size:]
#     return data.iloc[train_indices],data.iloc[test_indices]
    

In [10]:
# train_set,test_set=split_train_test(housing,0.2)

In [11]:
# print(f"Rows in train set :{len(train_set)}\nRows in test set:{len(test_set)}\n")

In [12]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(housing , test_size=0.2,random_state=42)
print(f"Rows in train set :{len(train_set)}\nRows in test set:{len(test_set)}\n")

Rows in train set :404
Rows in test set:102



In [13]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for tain_index ,test_index in split.split(housing,housing['CHAS']):
    strat_train_set=housing.loc[tain_index]
    strat_test_set=housing.loc[test_index]

In [14]:
strat_test_set['CHAS'].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

In [15]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [16]:
# 95/7
#

In [17]:
# 376/28

In [18]:
housing=strat_train_set.copy()

## Looking for Correlations

In [19]:
corr_maxtrix= housing.corr()

In [20]:
corr_maxtrix['MEDV'].sort_values(ascending=False)

MEDV       1.000000
RM         0.680857
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [21]:
# from pandas.plotting import scatter_matrix
# attributes=['MEDV', 'RM','ZN',"LSTAT"]
# scatter_matrix(housing[attributes],figsize=(12,10))

In [22]:
# housing.plot(kind="scatter",x="RM",y="MEDV",alpha=1)

##  Trying Attribute Combinations

In [23]:
#we have tex and number of room so we will make new attribute giving text per room
# housing['TaxPerRM']=housing['TAX']/housing['RM']

In [24]:
# housing.head()

In [25]:
# corr_matrix=housing.corr()
# corr_matrix['MEDV'].sort_values(ascending=False)

In [26]:
# housing.plot(kind="scatter",x="TaxPerRM",y="MEDV",alpha=1)

In [27]:
#Makeing features and labels from housing (data)
housing=strat_train_set.drop('MEDV',axis=1)
housing_labels=strat_train_set['MEDV'].copy()

## Missing Attributes

In [28]:
# To take care of missing attributes , we have 3 options:
#     1. Dlt the missing data points
#     2. Get rid of the whole attributes
#     3. set the value to some value(1,mean or median)

In [29]:

a= housing.dropna(subset=['RM']) #option 1 #
a.shape
#Note that the original housing dataframe will remain unchange 

(399, 13)

In [30]:
housing.drop('RM',axis=1).shape #option 2
#Note that the original housing dataframe will remain unchange 

(404, 12)

In [31]:
median=housing['RM'].median()#computing median for option 3

In [32]:

housing['RM'].fillna(median) #option 3
#Note that the original housing dataframe will remain unchange 

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [33]:
housing.shape

(404, 13)

In [34]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279481   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.716784   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.876500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [35]:
from sklearn.impute import SimpleImputer as Imputer
imputer=Imputer(strategy='median')
imputer.fit(housing)

SimpleImputer(strategy='median')

In [36]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.20900e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [37]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  399.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279481   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.716784   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.876500   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630500   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [38]:
X = imputer.transform(housing)


In [39]:
housing_trans = pd.DataFrame(X , columns=housing.columns)

In [40]:
housing_trans.describe() #transforemed housing(data/features)

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.278609   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712366   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.209000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

## Creating Pipeline

In [41]:
    from sklearn.pipeline import Pipeline
    from sklearn.preprocessing import StandardScaler
    
    my_pipeline=Pipeline([
        ('imputer',Imputer(strategy="median")),
        ('std_scaler',StandardScaler()),
    ])

In [42]:
#fit and transform using sklearn (output = array)
housing_num_trans=my_pipeline.fit_transform(housing)

In [43]:
housing_num_trans.shape

(404, 13)

# Selecting a desired model for Our Housing Data

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
model =RandomForestRegressor()
# model= DecisionTreeRegressor()
# model=LinearRegression()
model.fit(housing_num_trans , housing_labels)

RandomForestRegressor()

In [45]:
some_data =housing.iloc[:5]#iloc--> index location

In [46]:
some_labels=housing_labels[:5]


In [47]:
prepared_data=my_pipeline.transform(some_data)#passing data through pipline

In [48]:
model.predict(prepared_data)

array([22.088, 25.382, 16.442, 23.278, 23.584])

In [49]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

# Evaluating the Model

In [50]:
from sklearn.metrics import mean_squared_error
housing_prediction = model.predict(housing_num_trans)
mse = mean_squared_error(housing_labels,housing_prediction)
rmse =np.sqrt(mse)

In [51]:
rmse

1.3073085135135267



# Cross Validation for choosing the better tech.

In [52]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score( model ,housing_num_trans ,housing_labels, scoring="neg_mean_squared_error" ,cv=10)
rmse_scores = np.sqrt(-scores)

In [53]:
rmse_scores 

array([2.79874618, 2.88422338, 4.31261326, 2.53322514, 3.33144376,
       2.67162878, 4.76422398, 3.28865157, 3.26291432, 3.3031275 ])

 ## Printing scores (scores ,mean standard deviation)

In [54]:
def print_score(scores):
    print("Scores: " ,scores)
    print("Mean : " ,scores.mean())
    print("Standard deviation :" ,scores.std())

In [55]:
print(str(model))
print_score(rmse_scores)


RandomForestRegressor()
Scores:  [2.79874618 2.88422338 4.31261326 2.53322514 3.33144376 2.67162878
 4.76422398 3.28865157 3.26291432 3.3031275 ]
Mean :  3.3150797863846444
Standard deviation : 0.6764972868018597


## Saving The Model

In [56]:
from joblib import dump ,load
dump(model ,'Dragon.joblib')

['Dragon.joblib']

## Testing 

In [57]:
X_test =strat_test_set.drop('MEDV',axis=1)
Y_test =strat_test_set['MEDV'].copy()
X_test_prepared =my_pipeline.transform(X_test)
final_predictions= model.predict(X_test_prepared)
final_mse=mean_squared_error(Y_test,final_predictions)
final_rsme =np.sqrt(final_mse)
print(final_predictions[:10] ,list(Y_test)[:10])

[24.832 11.164 25.328 22.121 18.309 14.828 19.908 14.449 31.916 41.535] [16.5, 10.2, 30.1, 23.0, 14.4, 15.6, 19.4, 14.1, 30.3, 35.2]


In [58]:
final_rsme

3.005334184217044

## Using The Model

In [59]:
from joblib import dump ,load
import numpy as np
model =load('Dragon.joblib')

features =np.array([[-5.43942006, 4.12628155, -1.6165014, -0.67288841, -1.42262747,
       -11.44443979304, -49.31238772,  7.61111401, -26.0016879 , -0.5778192 ,
       -0.97491834,  0.41164221, -66.86091034]])
model.predict(features)

array([25.667])